# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0028_auto_20180402_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='drv_award_transaction_usaspend',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='drv_current_total_award_value_amount_adjustment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='drv_potential_total_award_value_amount_adjustment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='period_of_performance_current_end_date',
            field=models.TextField(help_text='The current end date of the period of performance', null=True, verbose_name='Period of Performance Current End Date'),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='period_of_performance_start_date',
            field=models.TextField(help_text='The period of performance start date', null=True, verbose_name='Period of Performance Start Date'),
        ),
    ]
