# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0028_auto_20180402_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='parent_award',
        ),
        migrations.RemoveField(
            model_name='transactionnormalized',
            name='drv_award_transaction_usaspend',
        ),
        migrations.RemoveField(
            model_name='transactionnormalized',
            name='drv_current_total_award_value_amount_adjustment',
        ),
        migrations.RemoveField(
            model_name='transactionnormalized',
            name='drv_potential_total_award_value_amount_adjustment',
        ),
    ]
