# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0029_remove_unused_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        )
    ]
