# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DUNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardee_or_recipient_uniqu', models.TextField(db_index=True)),
                ('legal_business_name', models.TextField(blank=True, null=True)),
                ('activation_date', models.DateField(blank=True, db_index=True, null=True)),
                ('deactivation_date', models.DateField(blank=True, db_index=True, null=True)),
                ('registration_date', models.DateField(blank=True, db_index=True, null=True)),
                ('expiration_date', models.DateField(blank=True, db_index=True, null=True)),
                ('last_sam_mod_date', models.DateField(blank=True, null=True)),
                ('ultimate_parent_unique_ide', models.TextField(blank=True, db_index=True, null=True)),
                ('ultimate_parent_legal_enti', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'duns',
            },
        ),
    ]
