# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_create_recipient_name_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
